spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 362361

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: warn
    com.cys.blog: warn
  file: log/blog-pro.log
